data "aws_caller_identity" "current" {}

# GitHub's OIDC signing certificate, fetched live rather than hardcoding a
# thumbprint - GitHub has rotated this before, and a stale hardcoded value
# would silently break every future deploy until someone noticed.
data "tls_certificate" "github_actions" {
  url = "https://token.actions.githubusercontent.com"
}

resource "aws_iam_openid_connect_provider" "github_actions" {
  url             = "https://token.actions.githubusercontent.com"
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [data.tls_certificate.github_actions.certificates[0].sha1_fingerprint]

  tags = {
    Name = "${var.project_name}-github-actions-oidc"
  }
}

# INTENTIONAL SCOPING - read before touching this trust policy:
#
# The `sub` claim condition below pins this role to exactly one GitHub
# branch in exactly one repo:
#   repo:${var.github_org}/${var.github_repo}:ref:refs/heads/main
#
# This is deliberate, not an oversight. It means:
#   - No other GitHub repo, anywhere, can ever assume this role.
#   - No other branch, PR, tag, or fork of THIS repo can assume it either -
#     a workflow run from a feature branch or a PR from a fork gets denied
#     by AWS before it ever reaches an AWS API call.
#   - Only a workflow triggered by a push to `main` in this exact repo can
#     get credentials.
#
# If you ever need to deploy from another branch, widen this condition on
# purpose (e.g. swap to a `StringLike` with a wildcard) - don't loosen it
# by accident while debugging.
resource "aws_iam_role" "github_actions_deploy" {
  name = "${var.project_name}-github-actions-deploy-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = {
        Federated = aws_iam_openid_connect_provider.github_actions.arn
      }
      Action = "sts:AssumeRole"
      Condition = {
        StringEquals = {
          "token.actions.githubusercontent.com:aud" = "sts.amazonaws.com"
          "token.actions.githubusercontent.com:sub" = "repo:${var.github_org}/${var.github_repo}:ref:refs/heads/main"
        }
      }
    }]
  })

  tags = {
    Name = "${var.project_name}-github-actions-deploy-role"
  }
}

# Least-privilege CI/CD policy: push images to this one repo, and trigger a
# deploy on this one instance. Nothing else - no read access to other AWS
# resources, no ability to touch IAM, no ability to reach any other EC2
# instance in the account.
resource "aws_iam_role_policy" "github_actions_deploy" {
  name = "${var.project_name}-github-actions-deploy"
  role = aws_iam_role.github_actions_deploy.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid = "EcrAuthToken"
        # Same documented AWS requirement as the k3s node role in
        # k3s_instance.tf: ecr:GetAuthorizationToken has no resource-level
        # permissions in IAM and must be granted on "*". Not an oversight.
        Effect   = "Allow"
        Action   = "ecr:GetAuthorizationToken"
        Resource = "*"
      },
      {
        Sid    = "EcrPushThisRepoOnly"
        Effect = "Allow"
        Action = [
          "ecr:BatchCheckLayerAvailability",
          "ecr:PutImage",
          "ecr:InitiateLayerUpload",
          "ecr:UploadLayerPart",
          "ecr:CompleteLayerUpload",
        ]
        Resource = aws_ecr_repository.app.arn
      },
      {
        Sid    = "SendDeployCommandToK3sNodeOnly"
        Effect = "Allow"
        Action = "ssm:SendCommand"
        Resource = [
          "arn:aws:ec2:${var.region}:${data.aws_caller_identity.current.account_id}:instance/${aws_instance.k3s.id}",
          "arn:aws:ssm:${var.region}::document/AWS-RunShellScript",
        ]
      },
      {
        Sid = "ReadDeployCommandResult"
        # ssm:GetCommandInvocation genuinely needs Resource "*" here:
        # the command ID is generated by AWS at SendCommand time, so there
        # is no ARN to scope to in advance. This is not a missed
        # tightening opportunity.
        Effect   = "Allow"
        Action   = "ssm:GetCommandInvocation"
        Resource = "*"
      },
    ]
  })
}
